# Artifical Neural Network
input --- >>> Hidden Layer --- >>> Output


to find accuracy of output  we will found cost function

-- when hidden layer get more than 2 then we will call it as Deep Neural Network

As we want cost function tendens to zero   so when output came we gave it to input or weight given to input not only input but intermeddite stages also 
this is called backprapogation

-- So weight get change or cost function is applied to all layers so when we want to backtrace then we can 

# Activation Funciton

it has 100+ type

In neural most used are 4


for error reduction we check it by activation funtion by each hidden layer


INPUT -- H1--(AF1)--H2--(AF2)--H3--(AF3)--OUTPUT

AF3-- mainly use Sigmoid funtion here


and remaining 3 is apply in middle in AF1 AF2


Activation Function 
1. Threshold -- -- function are in pdf
2. Sigmoid -- -- function are in pdf
3. Rectify -- -- function are in pdf
4. Hyperbolic Tangent -- -- function are in pdf





############################# To adjust weight we apply this method ###################################

--@@  Gradient Decent @@--
--@@  Schocastic Gradient Decent @@--

In [76]:
import pandas as pd
import matplotlib.pyplot as plt



In [77]:
df=pd.read_csv('bank.csv')

In [78]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

we will find that column that give that customer stay in bank or not

FEATURES-- so creditScore,Geography,Gender,Age,Tenure,Balance,NumberofProducts,HasCrCard,IsActiveMember,EstimatedSalary


LABEL-- Exited

In [79]:
features=df.iloc[:,3:13].values
features

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [80]:
label=df.iloc[:,-1].values
label

array([1, 0, 1, ..., 1, 1, 0])

# Categorical Data -- is Geography and Gender

To categorize into string into numeric data as processor do not understand

In [81]:
from sklearn.preprocessing import LabelEncoder

In [82]:
country=LabelEncoder()   

In [83]:
features[:,1]=country.fit_transform(features[:,1])

In [84]:
features

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [85]:
gender=LabelEncoder()

In [86]:
features[:,2]=gender.fit_transform(features[:,2])

In [87]:
features

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

# as country has got 0,1,2 value so it split it into as 2 as best so we create dummy variable 
this is as 

if france is present then 1 0 0  -- -- it means france is present and spain and germany is absent


this is done threw ONEHOTENCODER


In [112]:
from sklearn.preprocessing import OneHotEncoder

In [113]:
ohe=OneHotEncoder(categorical_features=[1])


In [114]:
features=ohe.fit_transform(features).toarray()

/home/siddhant/.local/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/home/siddhant/.local/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [115]:
features.astype(int)

array([[     1,      0,      0, ...,      1,      1, 101348],
       [     0,      1,      0, ...,      0,      1, 112542],
       [     1,      0,      0, ...,      1,      0, 113931],
       ...,
       [     1,      0,      0, ...,      0,      1,  42085],
       [     1,      0,      1, ...,      1,      0,  92888],
       [     1,      0,      0, ...,      1,      0,  38190]])

In [116]:
features.shape

(10000, 12)

In [117]:
features=features[:,1:]

In [118]:
pd.DataFrame(features).astype(int).head(5)

0   1    2   3   4   5       6   7   8   9       10
0   0   0  619   0  42   2       0   1   1   1  101348
1   1   0  608   0  41   1   83807   1   0   1  112542
2   0   0  502   0  42   8  159660   3   1   0  113931
3   0   0  699   0  39   1       0   2   0   0   93826
4   1   0  850   0  43   2  125510   1   1   1   79084

In [119]:
from sklearn.model_selection import train_test_split
train_fe,test_fe,train_la,test_la=train_test_split(features,label,test_size=.2)

In [120]:
# Applying Features Scaling
from sklearn.preprocessing import StandardScaler

In [121]:
sc=StandardScaler()

In [122]:
train_fe=sc.fit_transform(train_fe)

In [123]:
test_fe=sc.transform(test_fe)

# Apply Neural Networks

1. take input as number of features and decide some reandom weights close to 0  is given such tha weight do not effect input -- input layers are 12

2. design 1st hidden layer  -- prefer to be avg of nurons in starting layer

3. design or assume number of nodes for sec hidden layer with its activation function   -- Activation function is applied everywhere except input layer

4. calculate predication with sigmoid activation function output and apply cost function to check the error

5. If error found then apply back propagation and adjust weight accordingly to get more and better output

6. Repeat 2 to 4 again if output is not acurrate

-- Backprapotion --weight adjust 

# ANN

In [124]:
import keras

In [125]:
# to create ANN model 

from keras.models import Sequential               # ANN initialize ----- Classifier Init

In [126]:
# to fill data in each layer 

from keras.layers import Dense                 # classifer fit data

In [127]:
# calling ANN model as classifier

clf=Sequential()

In [128]:
# Time for adding layers           ---- input go as input and first hidden layer

# Adding first input layer with hidden layer   ---  activation funcion is Rectify  -- kernel_initializer is for initialize it in one range
# input shape must be in tuple thats why we give (11,)
# units is avg of total coulumn   -- - -

clf.add(Dense(units=6,activation='relu',kernel_initializer='glorot_uniform',input_shape=(11,)))

In [129]:
clf.add(Dense(units=6,activation='relu',kernel_initializer='glorot_uniform'))

In [130]:
# we added 2 layer   now we finalizing output layer
clf.add(Dense(units=1,activation='sigmoid'))

In [131]:
# as all is in graph so we compile     now compile create model
# optimizer adam give backprapoagtion algo out of 2 
clf.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

#loss=multiple output comapre
#metics=accuracy in 

In [132]:
len(train_fe[0])

11

In [133]:
# fitting features and label data
# batch_size === how much data you want to sent if 1000000 is data and you want to compute only 10   
# epochs === is from input to output 1 epoch is completed then it go to input and repeated 100 timees
clf.fit(train_fe,train_la,batch_size=10,epochs=10)

Epoch 1/10
8000/8000 [==============================] - 1s 120us/step - loss: 0.5128 - acc: 0.7952
Epoch 2/10
8000/8000 [==============================] - 1s 82us/step - loss: 0.4536 - acc: 0.8011
Epoch 3/10
8000/8000 [==============================] - 1s 82us/step - loss: 0.4356 - acc: 0.8105
Epoch 4/10
8000/8000 [==============================] - 1s 82us/step - loss: 0.4250 - acc: 0.8171
Epoch 5/10
8000/8000 [==============================] - 1s 83us/step - loss: 0.4160 - acc: 0.8222
Epoch 6/10
8000/8000 [==============================] - 1s 82us/step - loss: 0.4104 - acc: 0.8277
Epoch 7/10
8000/8000 [==============================] - 1s 83us/step - loss: 0.4063 - acc: 0.8320
Epoch 8/10
8000/8000 [==============================] - 1s 82us/step - loss: 0.4027 - acc: 0.8314
Epoch 9/10
8000/8000 [==============================] - 1s 83us/step - loss: 0.4005 - acc: 0.8320
Epoch 10/10
8000/8000 [==============================] - 1s 84us/step - loss: 0.3977 - acc: 0.8335


In [134]:
# now we are predicting the trained data
clf.predict(test_fe)

array([[0.2426432 ],
       [0.06798196],
       [0.7672243 ],
       ...,
       [0.13060221],
       [0.23375532],
       [0.13395873]], dtype=float32)